#!/bin/bash
set -ex

if [[ -n "$GITHUB_BASE_REF" ]] && [[ "$TEST_SUITE" == "lint" ]]; then
  # Run cardboardlinter, in case of pull requests
  cardboardlinter --refspec $GITHUB_BASE_REF -n auto
fi

if [[ "$TEST_SUITE" == "unittest" ]]; then
  nosetests tests --nocapture
  ./tests/test_server_package.sh
fi

if [[ "$TEST_SUITE" == "testscripts" ]]; then
   # test model training scripts
  ./tests/test_tts_train.sh
  ./tests/test_vocoder_gan_train.sh
  ./tests/test_vocoder_wavernn_train.sh
fi
